// Mock data for development - replace with actual API calls
import type { Teacher, Student, Subject, Class, Bus } from "@/types"

export const mockTeachers: Teacher[] = [
  {
    id: 1,
    teacherId: "T001",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@school.com",
    phone: "123-456-7890",
    address: "123 Main St",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    subjects: ["Math", "Physics"],
    classes: ["10A", "11B"],
    sex: "male",
    bloodType: "O+",
    birthday: "1985-05-15",
  },
  {
    id: 2,
    teacherId: "T002",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@school.com",
    phone: "123-456-7891",
    address: "456 Oak Ave",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    subjects: ["English", "Literature"],
    classes: ["9A", "10B"],
    sex: "female",
    bloodType: "A+",
    birthday: "1988-08-22",
  },
  {
    id: 3,
    teacherId: "T003",
    firstName: "Mike",
    lastName: "Johnson",
    email: "mike.johnson@school.com",
    phone: "123-456-7892",
    address: "789 Pine St",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    subjects: ["Chemistry", "Biology"],
    classes: ["11A", "12A"],
    sex: "male",
    bloodType: "B+",
    birthday: "1982-12-10",
  },
  {
    id: 4,
    teacherId: "T004",
    firstName: "Sarah",
    lastName: "Wilson",
    email: "sarah.wilson@school.com",
    phone: "123-456-7893",
    address: "321 Elm St",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    subjects: ["History", "Geography"],
    classes: ["9B", "10C"],
    sex: "female",
    bloodType: "AB+",
    birthday: "1990-03-18",
  },
  {
    id: 5,
    teacherId: "T005",
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@school.com",
    phone: "123-456-7894",
    address: "654 Maple Ave",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    subjects: ["Computer Science", "Math"],
    classes: ["11C", "12B"],
    sex: "male",
    bloodType: "O-",
    birthday: "1987-07-25",
  },
]

export const mockStudents: Student[] = [
  {
    id: 1,
    studentId: "S001",
    firstName: "Alice",
    lastName: "Cooper",
    email: "alice.cooper@student.com",
    phone: "098-765-4321",
    address: "456 Oak Ave",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    grade: 10,
    class: "10A",
    sex: "female",
    bloodType: "A+",
    birthday: "2008-03-20",
  },
  {
    id: 2,
    studentId: "S002",
    firstName: "Bob",
    lastName: "Smith",
    email: "bob.smith@student.com",
    phone: "098-765-4322",
    address: "789 Pine St",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    grade: 11,
    class: "11A",
    sex: "male",
    bloodType: "B+",
    birthday: "2007-06-15",
  },
  {
    id: 3,
    studentId: "S003",
    firstName: "Carol",
    lastName: "Johnson",
    email: "carol.johnson@student.com",
    phone: "098-765-4323",
    address: "321 Elm St",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    grade: 9,
    class: "9A",
    sex: "female",
    bloodType: "O+",
    birthday: "2009-11-08",
  },
  {
    id: 4,
    studentId: "S004",
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@student.com",
    phone: "098-765-4324",
    address: "654 Maple Ave",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    grade: 12,
    class: "12A",
    sex: "male",
    bloodType: "AB+",
    birthday: "2006-01-30",
  },
  {
    id: 5,
    studentId: "S005",
    firstName: "Emma",
    lastName: "Davis",
    email: "emma.davis@student.com",
    phone: "098-765-4325",
    address: "987 Cedar Rd",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    grade: 10,
    class: "10B",
    sex: "female",
    bloodType: "A-",
    birthday: "2008-09-12",
  },
]

export const mockSubjects: Subject[] = [
  {
    id: 1,
    name: "Mathematics",
    teachers: ["John Doe", "David Brown"],
  },
  {
    id: 2,
    name: "Physics",
    teachers: ["John Doe"],
  },
  {
    id: 3,
    name: "Chemistry",
    teachers: ["Mike Johnson"],
  },
  {
    id: 4,
    name: "Biology",
    teachers: ["Mike Johnson"],
  },
  {
    id: 5,
    name: "English",
    teachers: ["Jane Smith"],
  },
  {
    id: 6,
    name: "Literature",
    teachers: ["Jane Smith"],
  },
  {
    id: 7,
    name: "History",
    teachers: ["Sarah Wilson"],
  },
  {
    id: 8,
    name: "Geography",
    teachers: ["Sarah Wilson"],
  },
  {
    id: 9,
    name: "Computer Science",
    teachers: ["David Brown"],
  },
]

export const mockClasses: Class[] = [
  {
    id: 1,
    name: "9A",
    capacity: 30,
    grade: 9,
    supervisor: "Jane Smith",
  },
  {
    id: 2,
    name: "9B",
    capacity: 28,
    grade: 9,
    supervisor: "Sarah Wilson",
  },
  {
    id: 3,
    name: "10A",
    capacity: 25,
    grade: 10,
    supervisor: "John Doe",
  },
  {
    id: 4,
    name: "10B",
    capacity: 27,
    grade: 10,
    supervisor: "Jane Smith",
  },
  {
    id: 5,
    name: "10C",
    capacity: 26,
    grade: 10,
    supervisor: "Sarah Wilson",
  },
  {
    id: 6,
    name: "11A",
    capacity: 24,
    grade: 11,
    supervisor: "Mike Johnson",
  },
  {
    id: 7,
    name: "11B",
    capacity: 23,
    grade: 11,
    supervisor: "John Doe",
  },
  {
    id: 8,
    name: "11C",
    capacity: 25,
    grade: 11,
    supervisor: "David Brown",
  },
  {
    id: 9,
    name: "12A",
    capacity: 22,
    grade: 12,
    supervisor: "Mike Johnson",
  },
  {
    id: 10,
    name: "12B",
    capacity: 21,
    grade: 12,
    supervisor: "David Brown",
  },
]

export const mockBuses: Bus[] = [
  {
    id: 1,
    busId: "BUS001",
    driverName: "Robert Carter",
    timeShifting: "Morning",
    phone: "555-0101",
    address: "45 Bus Depot Rd",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 2,
    busId: "BUS002",
    driverName: "Michael Johnson",
    timeShifting: "Evening",
    phone: "555-0102",
    address: "32 Transport Ave",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 3,
    busId: "BUS003",
    driverName: "James Wilson",
    timeShifting: "Day",
    phone: "555-0103",
    address: "78 Main Street",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 4,
    busId: "BUS004",
    driverName: "William Brown",
    timeShifting: "Morning",
    phone: "555-0104",
    address: "156 Oak Avenue",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 5,
    busId: "BUS005",
    driverName: "Thomas Davis",
    timeShifting: "Evening",
    phone: "555-0105",
    address: "234 Pine Road",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
]
